### ISSUE TITLE
Create boilerplate (depersonalized) version of this repo for shipyard org

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ecosystem-directory#133]
Once this work is in a finished enough state to recommend forking for others' projects, create a less IPFS-specific "boilerplate" version in (probably) the ipfs-shipyard org in order to give others both a clean starting point and to provide an example of how the app can be set up to meet a variety of needs. The work might involve:
- Changing IPFS colors/branding to an example alternative
- Changing filter criteria as an illustration of possibility
- Depersonalizing iconography and/or content (e.g. use Noun Project icons, cat photos etc)

**Comment by orvn** [comment]
> **Note:** boilerplate should be the upstream fork of this repo (i.e., the parent of the IPFS ecosystem directory). This way new features can be implemented in the boilerplate, and then pulled into the various forks, one of which will be this repo

**Comment by timelytree** [comment]
@jessicaschilling can you set up an empty repo for me to push the boilerplate version to?

**Comment by jessicaschilling** [comment]
@timelytree here you go: https://github.com/ipfs-shipyard/ecosystem-directory 😊

**Comment by orvn** [comment]
This boilerplate is complete, and is already in use for the Filecoin ecosystem as well!
