### ISSUE TITLE
Filter panel chiclets should be "or", not "and"

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ecosystem-directory#165]
Relayed from @thattommyhall: Filter panel chiclet doesn't do what's expected upon multi-selection — "in my head you are filtering for any of N industries, not each of N". 

Indeed, this is an expected e-commerce pattern — example from Amazon: 
![image](https://user-images.githubusercontent.com/1507828/123715267-2628b380-d835-11eb-824e-280f8d7b1687.png)

Regardless of final approach to "or" vs "and", let's consider the following:
- Remove "All" as it's pretty much guaranteed to get you to null results
- Consider replacing it with "Clear selection" in order to clear selection per filter category (more granular than just the "Clear x selected" at bottom of filter panel)

**Comment by jessicaschilling** [comment]
@D3AS8A, thoughts on this for something to address in the pre-public-launch queue?

**Comment by D3AS8A** [comment]
@jessicaschilling 

Re: “or” vs “and” in  filtter panel tag selection, we’ve huddled about this before and the determination at the time was that there would be instances of projects that could technically fit into multiple categories. 

I imagine the current implementation would feel more intuitive as this ecosystem grows (with a larger sample size to work from). 

> Right now, every category in the taxonomy is designed as an array—tags are inherently not mutually exclusive. The current implementation was meant to act as a type of drill down— allowing the user to start with a broad search and then refine to a narrow search as desired. 

@orun do you plan to implement any kind of setting in the project setting that allows an admin user to select “or” or “and”? 

- **_All_** serves as quick multi-chiclet selection option we use to address behavioral patterns seen with technically proficient where users click _all_ and then deselect only one item, in the interest of time. 

- What do you think of following the current information scent and keeping in clean by adding a “clear filters”  option right where the “_of_ “ appears? See image. 

<img width="468" alt="clear selected filters" src="https://user-images.githubusercontent.com/72217652/124039828-ad129300-d9d1-11eb-9eb3-6bbe640e50fc.png">

**Comment by jessicaschilling** [comment]
@D3AS8A Completely agree about this making more sense for larger sample sets, but also understand that for a 65-instance set of projects that @thattommyhall's comment makes sense as well.

If we have the ability to offer a config setting to choose between and/or on a per-repo basis without going out of scope, that would be great ... but if we only have one option, given that we suspect we'll be seeing a significant number of small-scale forks of this (for hackathons in particular), it might be better to use "or" rather than "and".

**Comment by orvn** [comment]
> If we have the ability to offer a config setting to choose between and/or on a per-repo basis without going out of scope

Should be okay, but let me make sure that there isn't anything else that might need to be considered (incl. different messaging that allows the user to infer what the filters are doing)

**Comment by orvn** [comment]
Adding this option as a feature in settings.

**Comment by orvn** [comment]
Pushed to production, with settings for:

1. Toggling behavior of selected tags between `or` and `and`
2. Hiding the `All` multi-tag selector in front of categories in the filters panel

```json
        "tagMatchType": "or",
        "excludeFilterAllTag": false
```

_(these settings can be found in `settings.json`)_
