### ISSUE TITLE
Changing the sort should reset the page number

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/ecosystem-directory#166]
If you sort by alphabetical order and go to page 2, then switch to sorting by time on IPFS you'll end up on page of that sort instead of resetting back to page 1 (which is how GitHub issues and I think most other places do it).

**Comment by jessicaschilling** [comment]
@aschmahmann, nice catch 😊  
@orvn @timelytree — can we please add this to the fixes for public launch? 🙏

**Comment by orvn** [comment]
Yes, thanks for reporting!
