### ISSUE TITLE
Put "other" at end (aka far right)

### ISSUE THREAD

**Issue by momack2** [ipfs/ecosystem-directory#167]
It seems slightly weird to me to have "other" in the logical middle of the list ahead of much more important categories like NFTs, DeFi, etc. Can we adjust to put those popular categories earlier in the list (ex before "integrations") and move "other" to the very far left?

**Comment by orvn** [comment]
Thanks for mentioning. Yeah, agree completely, the desire to custom sort these is in development already.

**Comment by jessicaschilling** [comment]
Thanks, @orvn — we'll need to treat this as a hard requirement for public launch.

**Comment by orvn** [comment]
> Thanks, @orvn — we'll need to treat this as a hard requirement for public launch.

Will do! 

Just for context here: the segment slider has some visual logic that is designed to avoid collision between labels and their respective stems, regardless of the data that they represent (category names, entries per category, screen size, etc.). Part of this logic includes the automatic ordering of the segments, which ensures that it looks as intended visually.

For the solution, we're adding an option to force any particular segment to the front or the back of the line.

**Comment by orvn** [comment]
There's now an option to force a category into the last position of the segment slider. It's set to `"other"` in `settings.json`. A category can also be set to first, although that isn't being used by the repo at this time (the rest of the segments are sorted by the app for the purpose of avoiding label and stem collision).
