### ISSUE TITLE
Minor Airtable-JSON script fixes

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ecosystem-directory#183]
Dropping two small problems in the Airtable-JSON script here; @orvn, you'd mentioned you also had some tweaks you wanted in mind, so let's please consider those here too.

- [x] File names for icon and logo are swapped in the export
- [x] Newline slash indicators seem to be blowing out in the build, breaking projects with multiple (for instance) tags:
```
    {
      "slug": "tooling",
      "tags": [
        "go-ipfs\", \"ipfs-cluster\", \"http-gateway"
      ]
````

**Comment by orvn** [comment]
Fixed this, as well as some other issues @jessicaschilling:

> * [x]  File names for icon and logo are swapped in the export
> * [x]  Newline slash indicators seem to be blowing out in the build, breaking projects with multiple (for instance) tags:

- [x] If either the logo or the icon file doesn't exist, the available logo/icon should be written to _both_ fields
- [x] Add trailing newline to json output, for more valid *nix markup
- [x] More detailed comments that explain what's happening in the script, step by step

The script can be re-run on any rows needed by unchecking/re-checking the checkbox (for inclusion in directory).
