### ISSUE TITLE
Defunct ecosystem partner in directory. Consider removal?

### ISSUE THREAD

**Issue by placer14** [ipfs/ecosystem-directory#236]
Temporal is listed in the IPFS ecosystem directory. Their website is broken and appears defunct. Might reach out to partner and update the directory as needed: 

https://ecosystem.ipfs.io/project/temporal

**Comment by orvn** [comment]
@placer14 👋 

FYI, they still seem [active on Github](https://github.com/RTradeLtd?q=temporal&type=all&language=&sort=)? (Temporal itself, as well as its docs had commits from this year, at least).

Their playground app and IPFS gateway isn't responding, so I wonder if it's a case of a server or service that's down?

```ini
;; ANSWER SECTION:
play.temporal.com.	60	IN	A	63.230.167.153

Request timeout for icmp_seq 0
```

**Comment by 2color** [comment]
Yeah Temporal can definitely be removed.
