### ISSUE TITLE
Set up final location for JSON data source

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ecosystem-directory#4]
Initial development work on this directory has been taking place concurrent to other teams' work on a PL-wide CRM database.    While it's not practical to add this directory's source data to the CRM database while both items are under active development, it's reasonable to expect we can consolidate these prior to launch.

- [ ] Add directory source data to master CRM database
- [ ] Re-link JSON extraction logic to master CRM database
- [ ] Test for expected behavior

**Comment by timelytree** [comment]
@jessicaschilling I wanted to touch base on what would be required from our end to close off this issue? Or is this fully in your own hands? :)

**Comment by jessicaschilling** [comment]
@timelytree This is blocked internally on the progress of an internal CRM ... no action from y'all required. We may need to touch base at some point in the future when we do migrate the data source, but not now.

**Comment by jessicaschilling** [comment]
Closing as this work has been paused internally.
