### ISSUE TITLE
Analytics using Countly

### ISSUE THREAD

**Issue by orvn** [ipfs/ecosystem-directory#64]
An analytics implementation with [Countly](https://count.ly/) should track the following:

- Basic hit tracking such as pageviews and sessions
- External link clicks
- Filter states
- Avoid the use of cookies, if possible
- Paths and referrers, especially internal to the app with virtualization of navigation
- Bot filtering or segmentation so real users can be distinguished

Because this is an SPA, we'll need to account for not only conventional navigation, but also virtualized.

**Comment by jessicaschilling** [comment]
Re-prioritizing this as P0 as metrics gathering is our biggest blocker to a formal launch at the moment. Thanks!

**Comment by orvn** [comment]
Understood!

**Comment by orvn** [comment]
Requested a new Countly app be created (for Ecosystem Directory), as it looks like these need to be manually configured first, before embedding the Web Analytics SDK into an app.

Here are the tracking objectives I have in mind (fyi @jessicaschilling )

- Fire Countly tag on page load (runs once as part of the page)
- Fire tag again on any virtualized route change
- Track button clicks as events
- Track external links as events
- Track params as a means for tracking search and filtering

**Comment by jessicaschilling** [comment]
@orvn - I believe @zebateira set up a new Countly app for you, but ping if there are any issues. A few notes:
- Header and footer can use the same tracking as what exists in https://github.com/ipfs/ipfs-website/tree/main/components - would be helpful to do so actually for interoperability in the long run
- The notes above sound great for data gathering for frequency of individual project pages and behavior for search/filter. Can we please break out behavior on the segment chart and featured projects sections, too? Perhaps to these end goals:
     - Most frequently clicked segments in the segment chart
     - Top "view all" clicks from within the segment chart
     - Which featured projects get the most clicks through to detail pages
- Can we also track 404s? @zebateira likely has some insight on how to do this in a consistent way with our other properties.

**Comment by zebateira** [comment]
Some hints:

- Use the [SDK](https://github.com/web3-storage/docs/blob/main/package.json#L13)
- Create a [helper file](https://github.com/web3-storage/docs/blob/main/docs/.vuepress/theme/utils/countly.js#L1) to init countly and easily track custom events
- Setup countly on [app init](https://github.com/web3-storage/docs/blob/main/docs/.vuepress/theme/enhanceApp.js#L5) and track route changes
- Setup [404s](https://github.com/web3-storage/docs/blob/main/docs/.vuepress/theme/layouts/404.vue#L39)
- Track any [custom events](https://github.com/web3-storage/docs/blob/main/docs/.vuepress/theme/components/Feedback.vue#L71) as required

Hope this helps!

**Comment by timelytree** [comment]
### Segment Chart

**Segment clicked**

```js
Countly.trackEvent('Segment Chart | Segment Clicked', {
  label: segment.label,
  slug: segment.slug
})
```

**View All button clicked**

```js
Countly.trackEvent('Segment Chart | View All Button Clicked', {
  label: category.label,
  slug: category.slug
})
```

### Featured Slider

**Project card clicked**

`from: Home Page | Detail Page`

```js
Countly.trackEvent('Featured Slider | Project Card Clicked', {
  name: project.name,
  slug: project.slug,
  from: this.parent
})
```

### Events

**Filter Panel Toggled**

`button: filters | x-icon | done`
`state: open | closed`

```js
Countly.trackEvent('Filter Panel Toggled', {
  button: 'filters',
  state: this.filterPanelOpen ? 'open' : 'closed'
})
```

**Sort-By Dropdown Toggled**

`state: open | closed`

```js
Countly.trackEvent('Sort-By Dropdown Toggled', {
  state: !this.closed ? 'open' : 'closed'
})
```

**Sort-By Option Selected**

```js
Countly.trackEvent('Sort-By Option Selected', {
  label: option.label,
  slug: option.slug
})
```

**Pagination Button Clicked**

`page: Number`

```js
Countly.trackEvent('Pagination Button Clicked', {
  page: <num>
})
```

**Results-Per-Page Dropdown Toggled**

`state: open | closed`

```js
Countly.trackEvent('Results-Per-Page Dropdown Toggled', {
  state: !this.closed ? 'open' : 'closed'
})
```

**Results-Per-Page Option Selected**

`option: Number`

```js
Countly.trackEvent('Results-Per-Page Option Selected', {
  option: <num>
})
```

**Grid-List View Toggled**

`view: list | grid`

```js
Countly.trackEvent('Grid-List View Toggled', {
  view: this.listViewActive ? 'list' : 'grid'
})
```

**Filter Chiclet Clicked**

`tag: all | <tag>`
`category: parent category of tag`
`state: on | off`

```js
Countly.trackEvent('Filter Chiclet Clicked', {
  tag,
  category,
  state
})
```

**Clear Filters Button Clicked**
`count: Number`

```js
Countly.trackEvent('Clear Filters Button Clicked', {
  count: this.selectedFiltersCount
})
```

**Filter Panel Search Input**

`query: search term with 500ms debounce`

```js
Countly.trackEvent('Filter Panel Search Input', {
  query
})
```

### Header/Footer

Links get automatically tracked by `Countly.track_links()`

### 404
```js
Countly.trackEvent('404_NOT_FOUND', {
  path: this.$route.path,
  referrer: document.referrer
})
```

### Query param string

Track URL query param string when interacting with project filtering system. Since every param change is already tracked individually as per the list above, this tracker exists as an added layer for testing.

**Comment by jessicaschilling** [comment]
@timelytree it's beautiful! Thank you. 😊

**Comment by timelytree** [comment]
Noting for future reference/remembering → the `url` field on Countly initialization needs to point to the _server that's running Countly_ and not to the main site URL as initially thought:

```js
Countly.init({
  app_key: APP_KEY,
  url: SERVER_URL // ← not SITE_URL
})
```
