### ISSUE TITLE
Overall app polish

### ISSUE THREAD

**Issue by orvn** [ipfs/ecosystem-directory#68]
This is a large issue that will continue to stay open until this project meets the standard outlined in the design

**Comment by jessicaschilling** [comment]
@orvn Can we consider this the issue for final fit-and-finish check prior to formal launch, or should we open something separate for that?

**Comment by orvn** [comment]
@jessicaschilling: I think something separate would be best, actually when I reopened this, I didn't realize it had already reached the 10 linked pull request limit 🤦

**Comment by jessicaschilling** [comment]
Sounds good - I've opened https://github.com/ipfs/ecosystem-directory/issues/186 as a holding pen for fit-and-finish and minor functional issues. Thanks!
