### ISSUE TITLE
Add alternative data visualization (showcase)

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ecosystem-directory#9]
Per @autonome, we will need to add an alternative means of visualizing the data so that it can be presented as a static image **with all data on display**, most likely in a slide-deck context. This has been socialized as a treemap, so unless there's a compelling reason to use a different method, suggest we stay with that. This doesn't need to be specifically part of the ordinary presentation of the rest of the app, but it would be a nice touch to invoke it by a "view as treemap" element or similar.

Requirements:

- 16x9 aspect ratio (for ease of use in slide decks) view of data as treemap: ideally in Figma format but something CSS-based works too, particularly if we can find a nice way to launch it from the main app
- Each treemap segment must include category title
- Each treemap segment must include number of participants in respective category
- Each treemap segment must include as many logos as viable
     - Since not all logos will be included, need means for prioritizing logos that MUST appear

**Comment by orvn** [comment]
@autonome and @jessicaschilling: just a quick wrap up on this feature, with some instructions, now that it's merged in (will also add this to the _readme_).

***

## Synopsis

The alternative data visualization view for the purpose of using in presentations, getting a summary of the projects in the app (at least by logo), etc., is now available!

By default we've called this the _Showcase_, which is also the URL through which it's accessed—although this name _can_ be changed.

## Behavior

The showcase view, visible in its bare form at ecosystem.ipfs.io

Query params:
category taxonomy slug
md minimum projects with a tag to display in a medium block. default 10
lg minimum projects with a tag to display in a large block. default 25

**Comment by orvn** [comment]
@autonome and @jessicaschilling: just a quick wrap up on this feature, with some instructions, now that it's merged in (will also add this to the _readme_).

***

## Synopsis

The alternative data visualization is now available!

By default we've called this the _Showcase_, which is also the URL through which it's accessed. This name _can_ be changed.

## Behavior

- The showcase view is visible in its bare form at [ecosystem.ipfs.io/showcase](https://ecosystem.ipfs.io/showcase)
- It provides a logo-based visual summary of the projects in the app by category
- Each tag within the selected category is assigned a block
- The container for the tag is sized based on whether there's a small, medium, or large quantity of projects within it

## Customization

### Category

Customizing the view is done using GET parameters. You might notice that the base showcase link feels a little empty. 

Adding a target top-level `category` param to showcase solves this issue. Examples:
- [/showcase/?category=industry](https://ecosystem.ipfs.io/showcase/?category=industry)
- [/showcase/?category=focus](https://ecosystem.ipfs.io/showcase/?category=focus)
- [/showcase/?category=benefits](https://ecosystem.ipfs.io/showcase/?category=benefits)

> Note: This category selection will work for _both_ categories that allow one tag per project (category in which tags are mutually exclusive) and categories that allow multiple tags.

### Containers

Instances of this app may have varying quantities of projects. To help the showcase address both large and small ecosystems, there are params that define container limits. These define what the limits are in terms of number of projects that fit into medium, or large containers.

- `md` minimum projects with a tag to display in a medium container (default is 10, if no value is provided)
- `lg` minimum projects with a tag to display in a large container ((default is 25, if no value is provided)

Example use case: [/showcase/?category=focus&md=5&lg=15](https://ecosystem.ipfs.io/showcase/?category=focus&md=5&lg=15)

> Note: The Showcase view is designed to support rows of 5 logos, so setting `lg` and `md` as multiples of 5 is recommended for the ideal visual appearance.

### Location

- The showcase path may be redefined in the app's `settings.json` under the key `showcaseBaseRoute`
  - Currently implemented as: `"showcaseBaseRoute": "/showcase"`
- The showcase has no links, and is not discoverable by search engines

**Comment by jessicaschilling** [comment]
@orvn - this is awesome! Thanks much for adding that note to the main readme, too.
@autonome - please do let the AU folks know if you have any comments or questions. Thanks!
